### ISSUE TITLE
seems to be broken(or i suck)

### ISSUE THREAD

**Issue by maxiwee69** [tropicbliss/defenestrator#3]
`thread 'main' panicked at src/executor.rs:57:26:
Error while sending request: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.mojang.com")), port: None, path: "/profiles/minecraft", query: None, fragment: None }, source: hyper::Error(Io, Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

i installed it using cargo install command you provided in one pof the other issues

**Comment by tropicbliss** [comment]
I have not been sniping for a long time and have not kept up with how the Mojang API has changed, so that's probably the reason, and you don't suck :)

I probably should just archive this. Use a more updated checker.
